spring:
  application:
    name: ${SERVER_NAME:ms-operator}

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

server:
  port: ${SERVER_PORT:8082}
  serviceUrl: ${SEARCH_SERVER:http://ms-search:8081/v1/items}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: false
    hostname: ${SERVER_NAME:ms-operator}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

app:
  cors:
    # Comma separated list (env: APP_CORS_ALLOWED_ORIGINS)
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:5173}
